timestamp: '2026-05-08T14:08:46'
tool: kobo
active_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
base_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
config_profile: ''
resolved_config:
  config_profile: ''
  config_profiles_dir: ''
  tool: kobo
  working_dir: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo
  questionnaire_file: Final_questionnaire_kobo_en_AFG_20250826013333_R11_copy.xlsx
  language: en
  iso3: AFG
  reference_mode: latest_template
  previous_round_file: ''
  templates_dir: C:/Users/edoar/WORK/FAO/repo/questionnaire_validation_revision/Questionnaires/Questionnaire
    Templates
  output_dir: C:\git\DIEM_Questionnaire_Validation\batch_output\kobo_cluster_ea_patch_check_20260508_140842\kobo_output
  validation_number: 501
  user_name: Edoardo
  kobo_options:
    country_specific_list_names:
    - crop
    - crop2
    - crop3
    - admin1
    - admin2
    - crp_main_sales2
    exclude_qnames_from_option_compare:
    - enumerator
    - enum_team
  questionnaire_path: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo\Final_questionnaire_kobo_en_AFG_20250826013333_R11_copy.xlsx
  output_base_dir: C:\git\DIEM_Questionnaire_Validation\batch_output\kobo_cluster_ea_patch_check_20260508_140842
resolved_run_paths:
  questionnaire_path: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo\Final_questionnaire_kobo_en_AFG_20250826013333_R11_copy.xlsx
  reference_path: C:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates\household_questionnaire_kobo_EN_template_20250708_ISO3_F2F.xlsx
  template_path: C:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates\household_questionnaire_kobo_EN_template_20250708_ISO3_F2F.xlsx
  reference_mode: latest_template
  language: en
  iso3: AFG
  working_dir: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo
  output_dir: C:\git\DIEM_Questionnaire_Validation\batch_output\kobo_cluster_ea_patch_check_20260508_140842\kobo_output
