timestamp: '2026-05-20T12:20:17'
tool: geopoll
active_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
base_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
config_profile: ''
resolved_config:
  templates_dir: c:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates
  working_dir: C:\git\DIEM_Questionnaire_Validation\tmp_curr
  questionnaire_file: DRC_R11_HH_questionnaire_Geopoll_TEST_CODESBROKEN.xlsx
  reference_mode: latest_template
  language: FR
  iso3: COD
  output_dir: C:\git\DIEM_Questionnaire_Validation\tmp_report_out3
  output_subfolder: geopoll_output
  previous_round_file: validated_questionnaire_kobo_ar_PSE_20250623155613.xlsx
  critical_sets_file: C:\git\DIEM_Questionnaire_Validation\configuration\critical_sets.yaml
resolved_run_paths:
  questionnaire_path: C:\git\DIEM_Questionnaire_Validation\tmp_curr\DRC_R11_HH_questionnaire_Geopoll_TEST_CODESBROKEN.xlsx
  reference_path: c:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates\household_questionnaire_geopoll_FR_template_20250708_ISO3.xlsx
  report_file: C:\git\DIEM_Questionnaire_Validation\tmp_report_out3\geopoll_output\report_geopoll_fr_COD_R11_20260520.xlsx
  validated_questionnaire_file: C:\git\DIEM_Questionnaire_Validation\tmp_report_out3\geopoll_output\validated_questionnaire_geopoll_fr_COD_R11_20260520.xlsx
