timestamp: '2026-05-08T10:40:04'
tool: geopoll
active_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
base_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
config_profile: ''
resolved_config:
  templates_dir: c:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates
  working_dir: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\geopoll
  questionnaire_file: GeoPoll_FAO_DRC_DIEM_Round_9_CATI_VF_copy.xlsx
  reference_mode: latest_template
  language: EN
  iso3: COD
  output_dir: C:\git\DIEM_Questionnaire_Validation\batch_output\20260508_103850
  output_subfolder: geopoll_output
  previous_round_file: ''
  critical_sets_file: C:\git\DIEM_Questionnaire_Validation\configuration\critical_sets.yaml
resolved_run_paths:
  questionnaire_path: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\geopoll\GeoPoll_FAO_DRC_DIEM_Round_9_CATI_VF_copy.xlsx
  reference_path: c:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates\household_questionnaire_geopoll_EN_template_20250708_ISO3.xlsx
  report_file: C:\git\DIEM_Questionnaire_Validation\batch_output\20260508_103850\geopoll_output\report_geopoll_en_COD_R18_20260508.xlsx
  validated_questionnaire_file: C:\git\DIEM_Questionnaire_Validation\batch_output\20260508_103850\geopoll_output\validated_questionnaire_geopoll_en_COD_R18_20260508.xlsx
