timestamp: '2026-05-08T10:39:17'
tool: kobo
active_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
base_config_file: C:\git\DIEM_Questionnaire_Validation\configuration\validation_config.yaml
config_profile: ''
resolved_config:
  config_profile: ''
  config_profiles_dir: ''
  tool: kobo
  working_dir: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo
  questionnaire_file: validated_questionnaire_kobo_fr_TCD_20250624134147_R9_copy.xlsx
  language: fr
  iso3: TCD
  reference_mode: previous_round
  previous_round_file: TCD_R8_HHQuestionnaire_Validated_R8_copy.xlsx
  templates_dir: c:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates
  output_dir: C:\git\DIEM_Questionnaire_Validation\batch_output\20260508_103850\kobo_output
  validation_number: 5
  user_name: codex_batch
  kobo_options:
    country_specific_list_names:
    - crop
    - crop2
    - crop3
    - admin1
    - admin2
    - crp_main_sales2
    exclude_qnames_from_option_compare:
    - enumerator
    - enum_team
  questionnaire_path: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo\validated_questionnaire_kobo_fr_TCD_20250624134147_R9_copy.xlsx
  output_base_dir: C:\git\DIEM_Questionnaire_Validation\batch_output\20260508_103850
resolved_run_paths:
  questionnaire_path: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo\validated_questionnaire_kobo_fr_TCD_20250624134147_R9_copy.xlsx
  reference_path: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo\TCD_R8_HHQuestionnaire_Validated_R8_copy.xlsx
  template_path: c:\Users\edoar\WORK\FAO\repo\questionnaire_validation_revision\Questionnaires\Questionnaire
    Templates\household_questionnaire_kobo_FR_template_20250708_ISO3_F2F.xlsx
  reference_mode: previous_round
  language: fr
  iso3: TCD
  working_dir: C:\Users\edoar\OneDrive\Desktop\Test_for_validation\kobo
  output_dir: C:\git\DIEM_Questionnaire_Validation\batch_output\20260508_103850\kobo_output
